- name: Install httpd in appservers
  hosts: all
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd 
        state: latest

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create blank file and add contents to it
      copy:
        dest: "/var/www/html/index.html"
        content: |
          This is a Nautilus sample file, created using Ansible!

    - name: Adding more info to index.html file
      lineinfile:
        path: /var/www/html/index.html
        line: 'Welcome to xFusionCorp Industries!'
        insertbefore: BOF 

    - name: Change file ownership and permissions
      file:
        path: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0777'
